name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  chat:
    name: Checks
    timeout-minutes: 45
    runs-on: [macos-latest]
    if: |
      (github.event.pull_request.commits == 1 && !contains(github.event.pull_request.title, '[skip ci]')) ||
      contains(github.event.pull_request.title, '[run ci]')
    steps:
      - uses: actions/checkout@v2
      - name: Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle check || bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Fasterer
        run: bundle exec fasterer
      - name: Fastlane
        env:
          PULL_REQUEST: ${{ github.event.pull_request._links.self.href }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIGGERS: "lib"
        run: |
          if [ $(ruby ./.github/scripts/check_changes.rb) = 0 ]; then
            echo "Project related folders were not touched"
          else
            bundle exec fastlane test
          fi
